### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by SuJiaKuan** [weitingchou/jagereye_ng#16]
After a long running of analyzer, following error occurs:
```
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fb041c989d8>, <Future finished exception=RuntimeError("can't 
start new thread",)>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 759, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 780, in _discard_future_result
    future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/distributed/client.py", line 840, in _update_scheduler_info
    self._scheduler_identity = yield self.scheduler.identity()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/distributed/core.py", line 474, in send_recv_from_rpc
    comm = yield self.live_comm()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/distributed/core.py", line 450, in live_comm
    connection_args=self.connection_args)
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/distributed/comm/core.py", line 187, in connect
    quiet_exceptions=EnvironmentError)
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/distributed/comm/tcp.py", line 321, in connect
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/tornado/tcpclient.py", line 226, in connect
    addrinfo = yield self.resolver.resolve(host, port, af)
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.6/dist-packages/tornado/netutil.py", line 364, in resolve
    None, _resolve_addr, host, port, family)
  File "/usr/local/lib/python3.6/dist-packages/tornado/platform/asyncio.py", line 161, in run_in_executor
    return self.asyncio_loop.run_in_executor(executor, func, *args)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 638, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 123, in submit
    self._adjust_thread_count()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 142, in _adjust_thread_count
    t.start()
  File "/usr/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

**Comment by uniray7** [comment]
I observe it, too.
The VM on AWS has 4GB memory

``` shell
ERROR:jagereye_ng:[NATS] <class 'nats.aio.errors.ErrStaleConnection'>
INFO:jagereye_ng:[NATS] disconnected
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f523e3dfd08>, <Future finished exception=RuntimeError("can't start new thread",)>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 759, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 780, in _discard_future_result
    future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/distributed/client.py", line 840, in _update_scheduler_info
    self._scheduler_identity = yield self.scheduler.identity()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/distributed/core.py", line 474, in send_recv_from_rpc
    comm = yield self.live_comm()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/distributed/core.py", line 450, in live_comm
    connection_args=self.connection_args)
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/distributed/comm/core.py", line 187, in connect
    quiet_exceptions=EnvironmentError)
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/distributed/comm/tcp.py", line 321, in connect
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/tornado/tcpclient.py", line 226, in connect
    addrinfo = yield self.resolver.resolve(host, port, af)
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.6/dist-packages/tornado/netutil.py", line 364, in resolve
    None, _resolve_addr, host, port, family)
  File "/usr/local/lib/python3.6/dist-packages/tornado/platform/asyncio.py", line 161, in run_in_executor
    return self.asyncio_loop.run_in_executor(executor, func, *args)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 638, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 123, in submit
    self._adjust_thread_count()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 142, in _adjust_thread_count
    t.start()
  File "/usr/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread                                                                                                                                                              [388/1823]
ERROR:jagereye_ng:[NATS] can't start new thread
INFO:jagereye_ng:[NATS] disconnected
INFO:jagereye_ng:[NATS] connection is closed
ERROR:jagereye_ng:[NATS] ERROR: <class 'nats.aio.errors.ErrStaleConnection'>
INFO:jagereye_ng:[NATS] disconnected
ERROR:jagereye_ng:[NATS] ERROR: can't start new thread
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f5268b9e9d8>, <Future finished exception=RuntimeError("can't start new thread",)>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 759, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 780, in _discard_future_result
    future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/distributed/client.py", line 840, in _update_scheduler_info
    self._scheduler_identity = yield self.scheduler.identity()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/distributed/core.py", line 474, in send_recv_from_rpc
    comm = yield self.live_comm()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/distributed/core.py", line 450, in live_comm
    connection_args=self.connection_args)
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/distributed/comm/core.py", line 187, in connect
    quiet_exceptions=EnvironmentError)
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/distributed/comm/tcp.py", line 321, in connect
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/tornado/tcpclient.py", line 226, in connect
    addrinfo = yield self.resolver.resolve(host, port, af)
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.6/dist-packages/tornado/netutil.py", line 364, in resolve
    None, _resolve_addr, host, port, family)
  File "/usr/local/lib/python3.6/dist-packages/tornado/platform/asyncio.py", line 161, in run_in_executor
    return self.asyncio_loop.run_in_executor(executor, func, *args)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 638, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 123, in submit
    self._adjust_thread_count()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 142, in _adjust_thread_count
    t.start()
  File "/usr/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
```

and I guess "at the same time", the api server also crash
err msg:
``` shell
<--- Last few GCs --->

[10294:0x2602890] 90134300 ms: Scavenge 26.6 (30.9) -> 25.6 (30.9) MB, 0.6 / 0.0 ms  allocation failure 
[10294:0x2602890] 90424098 ms: Scavenge 26.6 (30.9) -> 25.6 (30.9) MB, 0.5 / 0.0 ms  allocation failure 
[10294:0x2602890] 90712905 ms: Scavenge 26.6 (30.9) -> 25.6 (30.9) MB, 0.6 / 0.0 ms  allocation failure 
[10294:0x2602890] 91003528 ms: Scavenge 26.6 (30.9) -> 25.6 (30.9) MB, 0.5 / 0.0 ms  allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x6ae3b525739 <JSObject>
    0: builtin exit frame: concat(this=0xff6bedd0269 <JSArray[0]>,0xff6bedd0289 <JSArray[0]>)

    1: isConnected [/home/ubuntu/jagereye_ng/services/api/node_modules/mongodb-core/lib/connection/pool.js:554] [bytecode=0x8a0728ea289 offset=47](this=0xff6bedcf899 <Pool map = 0x2b23d2f1649>)
    2: _onTimeout [/home/ubuntu/jagereye_ng/services/api/node_modules/mongodb-core/lib/connection/pool.js:297]...

FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
 1: node::Abort() [node]
 2: 0x11ef43c [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 6: v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: v8::internal::Factory::NewJSObjectFromMap(v8::internal::Handle<v8::internal::Map>, v8::internal::PretenureFlag, v8::internal::Handle<v8::internal::AllocationSite>) [node]
 8: v8::internal::Factory::NewJSArray(v8::internal::ElementsKind, int, int, v8::internal::ArrayStorageAllocationMode, v8::internal::PretenureFlag) [node]
 9: v8::internal::ElementsAccessor::Concat(v8::internal::Isolate*, v8::internal::Arguments*, unsigned int, unsigned int) [node]
10: 0xb7e5c8 [node]
11: v8::internal::Builtin_ArrayConcat(int, v8::internal::Object**, v8::internal::Isolate*) [node]
12: 0x3dcf31c8697d
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! jagereye_ng@0.0.1 start: `NODE_ENV='$JAGERENV' node server.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the jagereye_ng@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-05-12T13_49_53_244Z-debug.log

```
