### ISSUE TITLE
AttributeError: 'Worker' object has no attribute 'global_models'

### ISSUE THREAD

**Issue by SuJiaKuan** [weitingchou/jagereye_ng#26]
Sometimes the GPU worker raises the following error:
```
INFO:jagereye_ng:Creating Analyzer, params: {'id': '5afe9e0acc255714dd0093f7', 'source': {'url': 'rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov', 'mode': 'streamin
g'}, 'name': 'GG', 'pipelines': [{'params': {'roi': [{'y': 0.02180282026529312, 'x': 0.6686198552449544}, {'y': 0.9375212918171287, 'x': 0.4796620562785311}, {'y': 0.719
4930844177966, 'x': 0.9883945402103064}], 'triggers': []}, 'type': 'IntrusionDetection'}]}
INFO:jagereye_ng:Starting Analyzer: 5afe9e0acc255714dd0093f7
INFO:jagereye_ng:Starts running Analyzer: GG
INFO:jagereye_ng:Opening video source: rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov
INFO:jagereye_ng:Starting reader thread
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Using selector: EpollSelector
INFO:jagereye_ng:Created an IntrusionDetector (roi: ((160.46876525878906, 3.4884512424468994), (115.11889350684746, 150.0034066907406), (237.21468965047353, 115.11889350
684746)), triggers: [], detect_threshold: 0.25)
distributed.worker - WARNING -  Compute Failed
Function:  run_model
args:      ('object_detection', [<jagereye_ng.io.streaming.VideoFrame object at 0x7f7ecc147fd0>, <jagereye_ng.io.streaming.VideoFrame object at 0x7f7ecc1474e0>])
kwargs:    {}
Exception: AttributeError("'Worker' object has no attribute 'global_models'",)

distributed.scheduler - ERROR - error from worker tcp://127.0.0.1:41984: 'Worker' object has no attribute 'global_models'
INFO:jagereye_ng:Reader thread is terminated
INFO:jagereye_ng:Analyzer terminated: GG
Process Process-154086:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "analyzer.py", line 91, in run_driver_func
    driver_func(signal, *argv[0])
  File "analyzer.py", line 233, in analyzer_main_func
    results = [p.run(frames, motion) for p in pipelines]
  File "analyzer.py", line 233, in <listcomp>
    results = [p.run(frames, motion) for p in pipelines]
  File "/home/jager/jagereye_ng/apps/intrusion_detection.py", line 427, in run
    catched = self._check_intrusion(f_detect.result())
  File "/usr/local/lib/python3.5/dist-packages/distributed/client.py", line 171, in result
    six.reraise(*result)
  File "/home/jager/.local/lib/python3.5/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/jager/.local/lib/python3.5/site-packages/jagereye_ng-0.0.1-py3.5.egg/jagereye_ng/gpu_worker/gpu_worker.py", line 40, in run_model
    return get_worker().global_models[name].run(*args)
AttributeError: 'Worker' object has no attribute 'global_models'
```

Before the error occurs, I have added 1 or 2 analyzers, and change their RTSP streaming URLs to wrong ones repeatedly. But I don't know why the actions will cause the error.

**Comment by weitingchou** [comment]
Does the GPU worker restart automatically, for unknown reason, before this error occurred? This could happen if GPU worker restarts after system booting, because currently we don't have a way to re-initialize GPU worker after it restarts along (see #14), and without re-initialization the "global_models" attribute won't be created.
